### ISSUE TITLE
Mod does not launch on 1.20.1

### ISSUE THREAD

**Issue by RhythmicSys** [ApfelRauber/InfiniteBannerStack#1]
Issue: Mod does not initialize and crashes the client on startup on 1.20.1
Minecraft version: `1.20.1`
Fabric Version: `0.14.21`
Mods:
- `fabric api` 
  - Version: `0.85.0+1.20.1`

- `infinite banner stack` 
  - Version: `1.0.1` (1.20-1.20.1 release)
Log: https://mclo.gs/vLx6CRh

**Comment by ApfelRauber** [comment]
Fixed, should work as intended now.
